# Site
name: '누리뉴스'
description: '최신 이슈, 심층 보도, 그리고 독자와 세상을 연결하는 누리뉴스입니다.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'leedongja111@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
menu_name_company: '매체 소개'
menu_name_contact: '문의하기'
menu_name_terms: '이용약관'

include: ["_pages"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

authors:
    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
pagination:
  enabled: true
  per_page: 5  # 전역 per_page 설정
  sort_field: date
  sort_reverse: true

company:
  name: "ABC뉴스"
  ceo: "홍길동"
  registration_number: "123-45-67890"
  address: "서울특별시 강남구 테헤란로 123"
  phone: "02-1234-5678"
  email: "contact@abcnews.co.kr"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
