backend:
  name: git-gateway
  branch: main

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"  # 게시물이 저장될 폴더를 _posts로 설정
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # 파일명 형식 설정
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list", default: "General" }
      - { label: "Tags", name: "tags", widget: "list" }
